apiVersion: v1
kind: Service
metadata:
  name: {{ include "ubuntu.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ubuntu.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    {{- include "ubuntu.selectorLabels" . | nindent 4 }}
